version: "3.7"
services:
  gitlab:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-gitlab
    container_name: gitlab
    # restart: always
    hostname: 'gitlab.agl-lab.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.agl-lab.com'
    ports:
      - '80:80'
      - '2022:22'
    volumes:
      - '/home/jake/agj-labs/persistent-storage/gitlab/config:/etc/gitlab'
      - '/home/jake/agj-labs/persistent-storage/gitlab/logs:/var/log/gitlab'
      - '/home/jake/agj-labs/persistent-storage/gitlab/data:/var/opt/gitlab'
      - '/home/jake/agj-labs/persistent-storage/gitlab/opt:/opt/gitlab'
  jenkins:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-jenkins
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
      - '2023:22'
    volumes: 
      - '/home/jake/agj-labs/persistent-storage/jenkins/jenkins_home:/var/jenkins_home'